// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwup5tvWmMlRsjf4jyImittl5ep0-WiI',
    appId: '1:312732952394:web:56c1a8ec942debd4f2c3b3',
    messagingSenderId: '312732952394',
    projectId: 'milovet',
    authDomain: 'milovet.firebaseapp.com',
    storageBucket: 'milovet.firebasestorage.app',
    measurementId: 'G-RSD1NP8J8S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQPaJi6T3WYwBO_sxlGAZrkldUGLFRl_w',
    appId: '1:312732952394:ios:abcce545dc0fd8eaf2c3b3',
    messagingSenderId: '312732952394',
    projectId: 'milovet',
    storageBucket: 'milovet.firebasestorage.app',
    iosBundleId: 'com.example.milovet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQPaJi6T3WYwBO_sxlGAZrkldUGLFRl_w',
    appId: '1:312732952394:ios:abcce545dc0fd8eaf2c3b3',
    messagingSenderId: '312732952394',
    projectId: 'milovet',
    storageBucket: 'milovet.firebasestorage.app',
    iosBundleId: 'com.example.milovet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWwup5tvWmMlRsjf4jyImittl5ep0-WiI',
    appId: '1:312732952394:web:4ca823c59728fcdef2c3b3',
    messagingSenderId: '312732952394',
    projectId: 'milovet',
    authDomain: 'milovet.firebaseapp.com',
    storageBucket: 'milovet.firebasestorage.app',
    measurementId: 'G-LS35CRND3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ773_UrEKvLEArRUfWTBZxYKBnq3Ww60',
    appId: '1:312732952394:android:32f47ddb98c3b255f2c3b3',
    messagingSenderId: '312732952394',
    projectId: 'milovet',
    storageBucket: 'milovet.firebasestorage.app',
  );

}